# Generated by Django 3.2.7 on 2021-09-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail200',
            field=models.ImageField(default=1, editable=False, upload_to='thumbs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail400',
            field=models.ImageField(default=1, editable=False, upload_to='thumbs'),
            preserve_default=False,
        ),
    ]
