# Generated by Django 3.2.7 on 2021-09-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210915_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TierSettings',
            new_name='TierSetting',
        ),
    ]
