# Generated by Django 3.2.7 on 2021-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tiersettings_tiersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttier',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
