# Generated by Django 3.2.7 on 2021-09-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_accounttier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail200',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail400',
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbs')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
            ],
        ),
    ]
