# Generated by Django 3.2.7 on 2021-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210915_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='size',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
