# Generated by Django 3.2.7 on 2021-09-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_thumbnail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='photo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.photo'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
